### ISSUE TITLE
Missing exclude breaks deploy

### ISSUE THREAD

**Issue by sasha42** [Miserlou/flask-zappa#6]
There aren't any exclude fields in the sample configurations, and by default flask-zappa looks for them. It doesn't gracefully fail and errors out:

``` bash
(venv)sasha:~/project$ flask-zappa deploy production test_settings.json
Deploying production
Traceback (most recent call last):
  File "/Users/sasha/project/venv/bin/flask-zappa", line 260, in <module>
    cli()
  File "/Users/sasha/project/venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sasha/project/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/sasha/project/venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sasha/project/venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sasha/project/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/sasha/project/venv/bin/flask-zappa", line 125, in deploy
    _package(environment, zappa_settings)
  File "/Users/sasha/project/venv/bin/flask-zappa", line 83, in _package
    exclude=settings['exclude'])
KeyError: 'exclude'
```

Removing `exclude=settings['exclude']` from the following code hacks around the issue:

``` python
zip_path = zappa.create_lambda_zip(lambda_name,
                                       handler_file=handler_file,
                                       exclude=settings['exclude'])
```

**Comment by Doerge** [comment]
Bajeesus. Thanks for reporting, and sorry. Will fix right away.

**Comment by Doerge** [comment]
Commit 1f4ad7f5351a99b58e14f8b64c6b34908d239391 fixes this issue.

The README have been updated by 3cefdd6a9e359abcc5c541174b34871c33ab3af8 to include the exclude parameter in the sample.

**Comment by Kisung** [comment]
it my errors out:

``` bash
(venv)ubuntu@ip-10-10-20-46:~/work/zappa$ flask-zappa deploy production test_settings.json
Deploying production
Traceback (most recent call last):
  File "/home/ubuntu/work/zappa/venv/bin/flask-zappa", line 263, in <module>
    cli()
  File "/home/ubuntu/work/zappa/venv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/work/zappa/venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/work/zappa/venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/work/zappa/venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/work/zappa/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/work/zappa/venv/bin/flask-zappa", line 128, in deploy
    _package(environment, zappa_settings)
  File "/home/ubuntu/work/zappa/venv/bin/flask-zappa", line 86, in _package
    exclude=exclude)
TypeError: create_lambda_zip() got an unexpected keyword argument 'exclude'

```

**Comment by Miserlou** [comment]
You must be using an old Zappa version? I'd try from HEAD.

(Please note that flask-zappa is still under development, thanks for being patient.)

**Comment by Doerge** [comment]
You probably need to do `pip install --upgrade --force-reinstall git+https://github.com/Miserlou/Zappa` to get the newest version if you already have the old version on your system.
